version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app # Mount the frontend code for hot reloading
      - /app/node_modules # Persist node_modules inside the container

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app # Mount the backend code for hot reloading
    environment:
      - FLASK_ENV=development # Run in development mode
